name: JWT Authentication

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_URI=mongodb://localhost:27017/authdb
    volumes:
      - mongo_data:/data/db
    networks:
      - jwt-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - jwt-app
    ports:
      - 4004:4004
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - jwt-app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  jwt-app:
    driver: bridge
