# Nome del workflow visualizzato in GitHub Actions
name: Deploy Backend to Railway

# Eventi che scatenano il workflow
on:
  push:
    branches:
      - main # Il branch su cui monitorare le modifiche
    paths:
      - "backend/**" # Il workflow si attiva solo se ci sono modifiche nella cartella 'frontend/'

# Lavori da eseguire
jobs:
  deploy-frontend:
    # L'ambiente su cui verrà eseguito il lavoro
    runs-on: ubuntu-latest

    # Passaggi del lavoro
    steps:
      # Checkout del codice del repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurazione dell'ambiente Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Specifica la versione di Node.js che usi per il frontend

      # Installazione delle dipendenze del frontend
      - name: Install Backend Dependencies
        run: npm install # O 'yarn install' se usi Yarn, o 'pnpm install' se usi pnpm
        working-directory: backend # Esegue il comando nella cartella 'frontend'

      # Esecuzione dei test del frontend
      - name: Check for Backend Test Script
        id: check_backend_test_script
        working-directory: backend
        run: |
          if jq -e '.scripts.test' package.json > /dev/null; then
            echo "has_test_script=true" >> $GITHUB_OUTPUT
          else
            echo "has_test_script=false" >> $GITHUB_OUTPUT
          fi

      # Costruzione del frontend (generazione dei file di produzione)
      - name: Build Backend
        run: npm run build # Assicurati di avere uno script 'build' nel tuo package.json del frontend
        working-directory: backend # Esegue il comando nella cartella 'frontend'

      # Deployment del frontend su Railway
      - name: Deploy Backend to Railway
        uses: railwayapp/action-deploy@v1
        with:
          # L'ID del servizio Railway per il tuo frontend (lo trovi nella dashboard di Railway)
          service: ${{secrets.RAILWAY_BACKEND_SVC_ID}}
          # Il token API di Railway, memorizzato come GitHub Secret
          token: ${{ secrets.RAILWAY_TOKEN }}
          # Specifica la sottocartella radice del servizio all'interno della monorepo
          root-path: backend
