name: Deploy Frontend to Railway

on:
  push:
    branches:
      - main
      - test-deploy
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{secrets.RAILWAY_FRONTEND_SVC_ID}}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v3

      - name: Install Node.js
        run: |
          apk update
          apk add nodejs npm

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Run test
        run: echo "test"

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Deploy on railway
        run: railway up --service=${{ env.SVC_ID }}
